### ISSUE TITLE
3.0版本的Time.php不见了

### ISSUE THREAD

**Issue by shenfeng07** [top-think/think-helper#15]
通过composer update从1.0.7更新到3.0.0后，Time.php不见了。

**Comment by yunwuxin** [comment]
3.0的不再包含Time

可以使用jenssegers/date

3.0是专门给tp5.2使用的  如果不是tp5.2可以继续使用旧版

**Comment by shenfeng07** [comment]
我用的tp5.1，composer update后就自动更新到3.0.0了，在tp5.1下直接composer require topthink/think-helper也是安装了3.0.0。官方文档上没有说明，建议说明一下和加一下版本限制

**Comment by yunwuxin** [comment]
说明你原来的依赖写的不对

**Comment by xiaobudie** [comment]
5.1需要的应该是2.0版本（根据captcha、migration的分支结构猜测），但是helper这里把2.0的分支覆盖了，直接奔到了3.0，导致5.1版本执行require或者update后无法正常使用。@yunwuxin

**Comment by yunwuxin** [comment]
@xiaobudie 这个包没有过2.0版本    5.1和之前都是用1.0的

**Comment by xiaobudie** [comment]
嗯，这个“2.0”我也只是猜测。
既然TP5.1和之前用的都是1.0版本，那发布3.0版本时，是否可以保留一下 1.0 的分支？要不然没了版本限制，composer都会直接更新到3.0，而3.0却是TP6.0专用。这样就导致TP5.1，helper功能缺失。@yunwuxin

**Comment by yunwuxin** [comment]
@xiaobudie 1.0的分支 就是master  这个没有改过  3.0是新建的一个分支
