### ISSUE TITLE
flip这个方法有错误，在框架里面调用出错

### ISSUE THREAD

**Issue by 956569011** [top-think/think-helper#23]
在框架里面调用出错提示 array_flip(): Can only flip STRING and INTEGER values!
think-helper/src/Collection.php

/**
     * 交换数组中的键和值
     *
     * @access public
     * @return static
     */
    public function flip()
    {
        return new static(array_flip($this->items));
    }

**Comment by imzhi** [comment]
这个是你使用上的问题
