### ISSUE TITLE
希望Arr类可添加中文注释

### ISSUE THREAD

**Issue by plamYuan** [top-think/think-helper#28]
希望Arr类可添加中文注释

**Comment by hulang** [comment]
别做梦了，yunwuxin 写的东西，从来都没有
1.中文注释
2.没有文档

**Comment by ken678** [comment]
具体去看laravel的文档吧
https://learnku.com/docs/laravel/10.x/helpers/14866#4478fb

**Comment by hulang** [comment]
> 具体去看laravel的文档吧 https://learnku.com/docs/laravel/10.x/helpers/14866#4478fb

好的。。
